import { useEffect, useMemo, useState } from 'react';
import { Camera, CheckCircle2, Clock3, FileText, Plus, Send, Trash2, X } from 'lucide-react';
import { supabase } from '../services/supabase';

const defaultAreas=['Entrance / lobby','Offices','Conference room','Kitchen / break room','Restrooms','Hallways','Warehouse / operations area'];
const defaultInventory=['Toilet paper','Paper towels','Hand soap','Trash liners'];
const nowLocal=()=>new Date().toISOString();
const timeLabel=value=>value?new Date(value).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'—';
const duration=(a,b)=>{if(!a||!b)return '—';const mins=Math.max(0,Math.round((new Date(b)-new Date(a))/60000));return `${Math.floor(mins/60)}h ${mins%60}m`;};
const blankArea=name=>({id:crypto.randomUUID(),name,completed:false,notes:''});
const blankItem=name=>({id:crypto.randomUUID(),name,before:'',added:'',remaining:''});

export function ServiceReportWorkspace({open,onClose}){
  const [profile,setProfile]=useState(null);const [customers,setCustomers]=useState([]);const [facilities,setFacilities]=useState([]);
  const [customerId,setCustomerId]=useState('');const [facilityId,setFacilityId]=useState('');const [recipient,setRecipient]=useState('');
  const [checkIn,setCheckIn]=useState('');const [checkOut,setCheckOut]=useState('');const [areas,setAreas]=useState(defaultAreas.map(blankArea));
  const [inventory,setInventory]=useState(defaultInventory.map(blankItem));const [issues,setIssues]=useState([]);const [photos,setPhotos]=useState([]);
  const [summary,setSummary]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const [reportId,setReportId]=useState(null);

  useEffect(()=>{if(open)bootstrap();},[open]);
  async function bootstrap(){setMessage('');const {data:{session}}=await supabase.auth.getSession();if(!session?.user)return setMessage('Please log in again.');const {data:p,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error||!p?.company_id)return setMessage(error?.message||'No company workspace found.');setProfile(p);const {data,error:cErr}=await supabase.from('customers').select('*').eq('company_id',p.company_id).order('name');if(cErr)return setMessage(cErr.message);setCustomers(data||[]);const mip=(data||[]).find(c=>c.name.toLowerCase().includes('mip'));if(mip){setCustomerId(mip.id);setRecipient(mip.email||mip.billing_email||'');await loadFacilities(mip.id,p.company_id);}}
  async function loadFacilities(id,companyId=profile?.company_id){if(!id)return setFacilities([]);const {data,error}=await supabase.from('facilities').select('*').eq('company_id',companyId).eq('customer_id',id).order('name');if(error)return setMessage(error.message);setFacilities(data||[]);if((data||[]).length===1)setFacilityId(data[0].id);}
  function selectCustomer(id){setCustomerId(id);setFacilityId('');const c=customers.find(x=>x.id===id);setRecipient(c?.email||c?.billing_email||'');loadFacilities(id);}
  function updateArea(id,patch){setAreas(v=>v.map(x=>x.id===id?{...x,...patch}:x));}
  function updateItem(id,patch){setInventory(v=>v.map(x=>x.id===id?{...x,...patch}:x));}
  async function uploadPhotos(files,areaId){if(!files?.length||!profile)return;setMessage('Uploading photos…');for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${profile.company_id}/${reportId||'draft'}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('service-report-photos').upload(path,file,{contentType:file.type,upsert:false});if(error){setMessage(error.message);continue;}const {data}=supabase.storage.from('service-report-photos').getPublicUrl(path);setPhotos(v=>[...v,{id:crypto.randomUUID(),areaId,url:data.publicUrl,name:file.name}]);}setMessage('Photos uploaded.');}
  const selectedCustomer=customers.find(x=>x.id===customerId);const selectedFacility=facilities.find(x=>x.id===facilityId);
  const completedCount=areas.filter(x=>x.completed).length;
  const generatedSummary=useMemo(()=>summary||`Cleaning service completed for ${selectedFacility?.name||selectedCustomer?.name||'the facility'}. ${completedCount} of ${areas.length} areas were marked complete. ${photos.length} photos were included. ${inventory.filter(x=>Number(x.added)>0).length} inventory items were restocked.${issues.length?` ${issues.length} issue${issues.length===1?' was':'s were'} documented.`:''}`,[summary,selectedFacility,selectedCustomer,completedCount,areas.length,photos.length,inventory,issues.length]);
  function payload(status='draft'){return {company_id:profile.company_id,customer_id:customerId||null,facility_id:facilityId||null,created_by:profile.id,customer_name:selectedCustomer?.name||'Customer',facility_name:selectedFacility?.name||selectedCustomer?.name||'Facility',recipient_email:recipient||null,service_date:new Date().toISOString().slice(0,10),check_in:checkIn||null,check_out:checkOut||null,status,summary:generatedSummary,areas,inventory,issues,photos,updated_at:nowLocal(),...(status==='shared'?{shared_at:nowLocal()}: {})};}
  async function save(status='draft'){if(!profile||!customerId)return setMessage('Select a customer.');setSaving(true);setMessage('');const row=payload(status);let result;if(reportId)result=await supabase.from('service_reports').update(row).eq('id',reportId).select().single();else result=await supabase.from('service_reports').insert(row).select().single();setSaving(false);if(result.error)return setMessage(result.error.message);setReportId(result.data.id);setMessage(status==='shared'?'Report marked as shared.':'Report saved.');return result.data;}
  function htmlReport(){const inv=inventory.filter(x=>x.name&&(x.before||x.added||x.remaining));const issueRows=issues.filter(x=>x.description);const gallery=photos.map(p=>`<figure><img src="${p.url}"/><figcaption>${areas.find(a=>a.id===p.areaId)?.name||'Service photo'}</figcaption></figure>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#172033;max-width:820px;margin:auto;padding:32px;background:#f5f7fb}.card{background:white;border-radius:20px;padding:24px;margin:16px 0;border:1px solid #e7ebf2}h1{margin:0 0 6px}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.meta div{background:#f6f8fc;padding:14px;border-radius:14px}.meta small{display:block;color:#667085}.ok{color:#12805c}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid #edf0f5}.gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.gallery img{width:100%;border-radius:14px;display:block}.gallery figcaption{font-size:13px;color:#667085;margin-top:5px}@media(max-width:600px){.meta,.gallery{grid-template-columns:1fr}}</style></head><body><div class="card"><small>FACILITY OS · CLEANING SERVICE REPORT</small><h1>${selectedCustomer?.name||'Customer'}</h1><p>${selectedFacility?.name||''}</p><div class="meta"><div><small>Date</small><strong>${new Date().toLocaleDateString('en-US')}</strong></div><div><small>Arrival</small><strong>${timeLabel(checkIn)}</strong></div><div><small>Departure</small><strong>${timeLabel(checkOut)}</strong></div><div><small>Duration</small><strong>${duration(checkIn,checkOut)}</strong></div><div><small>Areas completed</small><strong>${completedCount}/${areas.length}</strong></div><div><small>Photos</small><strong>${photos.length}</strong></div></div></div><div class="card"><h2>Service summary</h2><p>${generatedSummary}</p></div><div class="card"><h2>Areas completed</h2>${areas.map(a=>`<p class="${a.completed?'ok':''}">${a.completed?'✓':'○'} <strong>${a.name}</strong>${a.notes?` — ${a.notes}`:''}</p>`).join('')}</div>${inv.length?`<div class="card"><h2>Inventory</h2><table><tr><th>Item</th><th>Before</th><th>Added</th><th>Remaining</th></tr>${inv.map(i=>`<tr><td>${i.name}</td><td>${i.before||'—'}</td><td>${i.added||'—'}</td><td>${i.remaining||'—'}</td></tr>`).join('')}</table></div>`:''}${issueRows.length?`<div class="card"><h2>Issues found</h2>${issueRows.map(i=>`<p><strong>${i.priority||'Normal'}:</strong> ${i.description}</p>`).join('')}</div>`:''}${gallery?`<div class="card"><h2>Service photos</h2><div class="gallery">${gallery}</div></div>`:''}<p style="text-align:center;color:#667085">Generated by Facility OS</p></body></html>`;}
  async function share(){if(!checkOut)setCheckOut(nowLocal());const saved=await save('shared');if(!saved)return;const html=htmlReport();const file=new File([html],`${selectedCustomer?.name||'customer'}-cleaning-report-${new Date().toISOString().slice(0,10)}.html`,{type:'text/html'});const subject=`Cleaning Service Report — ${selectedFacility?.name||selectedCustomer?.name||''}`;const text=`Hello,\n\nYour cleaning service was completed. Arrival: ${timeLabel(checkIn)}. Departure: ${timeLabel(checkOut||nowLocal())}. Areas completed: ${completedCount}/${areas.length}. Photos included: ${photos.length}.\n\n${generatedSummary}\n\nFacility OS`;
    if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:subject,text,files:[file]});return;}catch(e){if(e.name==='AbortError')return;}}
    const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);window.location.href=`mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(text+'\n\nThe formatted photo report was downloaded. Please attach it to this email.')}`;
  }
  if(!open)return null;
  return <div className="reportBackdrop"><section className="reportWorkspace"><header><div><p>OPERATIONS</p><h1>Cleaning service report</h1><span>Document completion, inventory, time on site, issues, and proof photos.</span></div><button onClick={onClose}><X/></button></header>{message&&<div className="reportNotice">{message}</div>}<div className="reportGrid"><main>
    <section className="reportCard"><h2>Visit</h2><div className="reportFields"><label>Customer<select value={customerId} onChange={e=>selectCustomer(e.target.value)}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Facility<select value={facilityId} onChange={e=>setFacilityId(e.target.value)}><option value="">Select facility</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Email<input type="email" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="customer@email.com"/></label></div><div className="timeActions"><button className={checkIn?'done':''} onClick={()=>setCheckIn(nowLocal())}><Clock3/> {checkIn?`Checked in ${timeLabel(checkIn)}`:'Start visit'}</button><button className={checkOut?'done':''} onClick={()=>setCheckOut(nowLocal())}><CheckCircle2/> {checkOut?`Checked out ${timeLabel(checkOut)}`:'Complete visit'}</button><strong>{duration(checkIn,checkOut)}</strong></div></section>
    <section className="reportCard"><div className="reportCardHead"><h2>Areas</h2><button onClick={()=>setAreas(v=>[...v,blankArea('New area')])}><Plus/> Add</button></div>{areas.map(a=><div className="areaRow" key={a.id}><input type="checkbox" checked={a.completed} onChange={e=>updateArea(a.id,{completed:e.target.checked})}/><input value={a.name} onChange={e=>updateArea(a.id,{name:e.target.value})}/><input placeholder="Notes" value={a.notes} onChange={e=>updateArea(a.id,{notes:e.target.value})}/><label className="photoButton"><Camera/> Photos<input type="file" accept="image/*" multiple capture="environment" onChange={e=>uploadPhotos([...e.target.files],a.id)}/></label><button onClick={()=>setAreas(v=>v.filter(x=>x.id!==a.id))}><Trash2/></button></div>)}</section>
    <section className="reportCard"><div className="reportCardHead"><h2>Inventory</h2><button onClick={()=>setInventory(v=>[...v,blankItem('New item')])}><Plus/> Add</button></div><div className="inventoryHeader"><span>Item</span><span>Before</span><span>Added</span><span>Remaining</span><span/></div>{inventory.map(i=><div className="inventoryRow" key={i.id}><input value={i.name} onChange={e=>updateItem(i.id,{name:e.target.value})}/><input inputMode="numeric" value={i.before} onChange={e=>updateItem(i.id,{before:e.target.value})}/><input inputMode="numeric" value={i.added} onChange={e=>updateItem(i.id,{added:e.target.value})}/><input inputMode="numeric" value={i.remaining} onChange={e=>updateItem(i.id,{remaining:e.target.value})}/><button onClick={()=>setInventory(v=>v.filter(x=>x.id!==i.id))}><Trash2/></button></div>)}</section>
    <section className="reportCard"><div className="reportCardHead"><h2>Issues</h2><button onClick={()=>setIssues(v=>[...v,{id:crypto.randomUUID(),priority:'Normal',description:''}])}><Plus/> Add issue</button></div>{!issues.length&&<p className="muted">No issues found.</p>}{issues.map(i=><div className="issueRow" key={i.id}><select value={i.priority} onChange={e=>setIssues(v=>v.map(x=>x.id===i.id?{...x,priority:e.target.value}:x))}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select><input placeholder="Describe the issue" value={i.description} onChange={e=>setIssues(v=>v.map(x=>x.id===i.id?{...x,description:e.target.value}:x))}/><button onClick={()=>setIssues(v=>v.filter(x=>x.id!==i.id))}><Trash2/></button></div>)}</section>
  </main><aside><section className="reportCard sticky"><FileText/><h2>Report preview</h2><div className="previewMetrics"><div><strong>{completedCount}/{areas.length}</strong><span>Areas</span></div><div><strong>{photos.length}</strong><span>Photos</span></div><div><strong>{duration(checkIn,checkOut)}</strong><span>Duration</span></div></div><label>Summary<textarea rows="7" value={summary} onChange={e=>setSummary(e.target.value)} placeholder={generatedSummary}/></label><div className="photoStrip">{photos.slice(0,6).map(p=><img key={p.id} src={p.url}/>)}</div><button className="saveReport" disabled={saving} onClick={()=>save(checkOut?'completed':'draft')}>{saving?'Saving…':'Save report'}</button><button className="sendReport" onClick={share}><Send/> Share / email report</button><small>On iPhone, the Share Sheet opens so you can select Mail and send the formatted report with its photos.</small></section></aside></div></section></div>;
}
