import fs from 'node:fs';
const path='src/app/App.jsx';
let source=fs.readFileSync(path,'utf8');
if(!source.includes("import { CommunicationHub } from './components/CommunicationHub';")) source=source.replace("import { ContractorsWorkspace } from './components/ContractorsWorkspace';","import { ContractorsWorkspace } from './components/ContractorsWorkspace';\nimport { CommunicationHub } from './components/CommunicationHub';");
source=source.replace("['customers','Customers',UsersRound],['contacts','Contacts',CircleUserRound],['quotes','Quotes',FileText],['facilities','Facilities',Building2]","['customers','Customers',UsersRound],['contacts','Contacts',CircleUserRound],['communications','Communications',Mail],['quotes','Quotes',FileText],['facilities','Facilities',Building2]");
if(!source.includes("page==='communications') content=<CommunicationHub")) source=source.replace("else if(page==='work-orders') content=<WorkOrdersPage data={data} companyId={profile.company_id} profile={profile} reload={reload}/>;","else if(page==='communications') content=<CommunicationHub data={data}/>;\n    else if(page==='work-orders') content=<WorkOrdersPage data={data} companyId={profile.company_id} profile={profile} reload={reload}/>;");
source=source.replace("<Button variant=\"secondary\" onClick={()=>editCustomer(customer)}>Edit</Button>\n          <Button onClick={()=>setPage('quotes')}><Plus size={16}/> New quote</Button>","<Button variant=\"secondary\" onClick={()=>editCustomer(customer)}>Edit</Button>\n          <Button variant=\"light\" onClick={()=>setPage('communications')}><Mail size={16}/> Message</Button>\n          <Button onClick={()=>setPage('quotes')}><Plus size={16}/> New quote</Button>");
fs.writeFileSync(path,source);
console.log('Aurora v3.24 communication integration applied.');
